### PR TITLE
Board

### PR DESCRIPTION
**Pull request by petterdaae**
I started implementing some sort of board-loader. Shout out if you disagree!

### CODE REVIEW

**Review by RuneThe — APPROVED** [review]
Seems like a good and flexible idea.  
Please make good documentation of value->tile function, 
to assure easy integration with tile-class.

**Review by AndreasCanAtakan — CHANGES_REQUESTED** [review]
Looks very good!

I would advise to switch the ITile references to Tile references. I changed the package structure to use classes (Tile) instead of interfaces (ITile) in my latest pull request, makes it easier to create future extensions.

**Comment by petterdaae** [comment]
> Seems like a good and flexible idea.
> Please make good documentation of value->tile function,
> to assure easy integration with tile-class.

I will! :D

**Comment by petterdaae** [comment]
> Looks very good!
> 
> I would advise to switch the ITile references to Tile references. I changed the package structure to use classes (Tile) instead of interfaces (ITile) in my latest pull request, makes it easier to create future extensions.

Hmm, ok. I'm not completely sure if I agree. But we can do it for now :) If you merge your branch first, I will fix it the conflicts when I merge mine :)

**Comment by AndreasCanAtakan** [comment]
@petterdaae i understand.

I was originally hesitant to "over-use" java interfaces given the following dilemma: given that interface B extends interface A, and that class X implements interface B and class Y implements interface A, then the methods in interface A need to be implemented twice, in both class X and class Y. I thought it would be better to just use classes as you can easily extend them and we avoid having to copy a lot of code.

But that's just my two cents, that do you guys think?

**Comment by petterdaae** [comment]
@AndreasCanAtakan Ok, I agree :) But would'nt it be better to use an abstract class then? Or are you going to use the base class as well, for example for simpler tile types? In that case, it's probably cool.

**Comment by AndreasCanAtakan** [comment]
> @AndreasCanAtakan Ok, I agree :) But would'nt it be better to use an abstract class then? Or are you going to use the base class as well, for example for simpler tile types? In that case, it's probably cool.

Super :) I was thinking that we probably need the regular Tile type as well, for drawing regular tiles on the board, so I think we can keep Tile as a class and not an abstract class.

Btw, just want to make sure. The project presentation we will have during a lecture, is next week right? (i.e. not today)

**Comment by petterdaae** [comment]
@AndreasCanAtakan Ok, sounds nice! Yes, next week :)

**Pull request merged**
