### PR TITLE
Apply method on LaserEvent

### PR DESCRIPTION
**Pull request by AndreasCanAtakan**

### CODE REVIEW

**Comment by AndreasCanAtakan** [comment]
Check note in apply method in LaserEvent.java

**Review by RuneThe — APPROVED** [review]
Check laser.class. 
Has implemented damage to robot on given board where it is hit by laser.

**Review by petterdaae — APPROVED** [review]

**Comment by AndreasCanAtakan** [comment]
@RuneThe Yes, that is a very good point. But is it more correct/easier for Petter and Dovydas to use the apply method in the event, rather than the laser class?

I am either way open for any of the approaches :)

**Comment by RuneThe** [comment]
Maybe we need to keep both doors open until we have them in the loop. If they are best supported in their tasks, it will be faster implemented. Is there other functions also clever to have in the apply(); so it is made as easy as possible to implement. Now is the point where we have a lot of options because of our broad appoach....

**Comment by petterdaae** [comment]
Damage should be done in both the laser class and in the apply method. The apply method is just a silly way of implementing animation :)

**Comment by RuneThe** [comment]
If damage happens in both places, in my head this will lead to double damage on that robot. Anyone care to explain if I am wrong?

**Comment by petterdaae** [comment]
apply() is called on a copy of the board, so no double damage :) again, it is just a silly way of implementing animations

**Comment by AndreasCanAtakan** [comment]
That clears it up :) If it looks ok, @petterdaae , then I'll just merge it

**Comment by petterdaae** [comment]
yes :)

**Review by dsp0011 — APPROVED** [review]

**Pull request merged**
