### PR TITLE
update Oblig2.md

### PR DESCRIPTION
**Pull request by petterdaae**

### CODE REVIEW

**Review by AndreasCanAtakan — APPROVED** [review]

**Review by RuneThe — APPROVED** [review]

**Comment by RuneThe** [comment]
Robot can have options to do repairs, from option-card?

**Review by PabloDons — CHANGES_REQUESTED** [review]
I would personally add key libraries to the set of technical tools. Thoughts?

**Comment by petterdaae** [comment]
@PabloDons ok, do you mean like LibDGX?

**Comment by PabloDons** [comment]
Exactly. Also java-websocket. JUnit would fall under this category too, so I think it's a good idea.

**Comment by petterdaae** [comment]
Ok, nice, I will add it!

**Review by dsp0011 — COMMENTED** [review]
approved

**Pull request merged**
